### ISSUE TITLE
sort line-count-by-author list by line-count

### ISSUE THREAD

**Issue by dezren39** [asharov/git-hammer#14]
this will also improve color distribution for the more significant committers. especially useful when you've got more than a dozen comitters and so only 'a b or c' names show up. in my case, some are dupes, my mailmap isn't perfect across all the repos at once yet. also can't see the line-count with the list like that

**Comment by asharov** [comment]
Thanks, that's a good idea! I should also figure out a way to display the legend better so it doesn't overlap with the information.

One thing I might also do quickly: internally there is functionality to limit the number of committers to require at least a certain number of lines (or tests) to make them appear in the graph. That is not currently exposed but I suppose I could add an option for it.

**Comment by asharov** [comment]
This was fixed in PR #19
