### ISSUE TITLE
Group entries based on author name

### ISSUE THREAD

**Issue by dkorobtsov** [asharov/git-hammer#27]
Noticed following issue - all summaries / graphs usually show output like:

| Author | Tests |  
|----------|----|
| Author B | 2  | 
| Author A | 12 |   
| Author B | 5  | 
| Author A | 7  | 
| Author C | 12  | 
| Author C | 5  | 
| Author C | 3 | 

Suppose reason is that author email changed at certain moment.
Wonder if it's possible to add option to group results by name?

**Comment by asharov** [comment]
Git Hammer relies on Git itself for this functionality. Git has a feature called mailmap file that can be used to define which names and/or emails should be treated as the same person. I found a nice explanation of how to create a mailmap file on the Atlassian blog: https://blog.developer.atlassian.com/aliasing-authors-in-git/

If you need further help, I'm happy to try, but I'm not an expert in this, and my mailmap file creation often ends up experimenting and running `git shortlog -se` until I'm happy with the results.

**Comment by dkorobtsov** [comment]
@asharov thank you! .mailmap aliases work just fine :-)
