### ISSUE TITLE
Use JSON array instead of Postgres ARRAY

### ISSUE THREAD

**Issue by asharov** [asharov/git-hammer#4]
Using the ARRAY type in the database requires using Postgres. Switching this type to JSON (and always putting an array there) would allow using also MySQL and SQLite. SQLite especially would be nice for a better standalone program experience.

**Comment by jawahar273** [comment]
Why can we try this method to convert array into json
https://github.com/jawahar273/practNLPTools-lite/blob/master/pntl/db/json_field.py

**Comment by asharov** [comment]
Thanks for your suggestion @jawahar273 . I ended up going with the JSONType from the SQLAlchemy-Utils package https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html which I presume is based on a similar idea.
